### ISSUE TITLE
Oberflächenoptimierung

### ISSUE THREAD

**Issue by Xerosia99** [Hummeltron/SBV-AES#49]
Oberflächenliste

(optional) Bessere Startseite ?: wenn man das Programm startet kommt man auf den Klassenlayer. Kann man da was schöneres drausmachen? So "das ist die Bücherverwaltungssoftware" bla bla  

die Ganzen Preise mit eurozeichen und zwei nachkomma stellen

optional: Statt SBV – AES das Schullogo?

!!!man kann keine bücher bei Schüler entfernen !!!

Eingedeutscht muss noch folgendes:

Klassenlayer -> tabelle obersteszeile

Klassenlayer -> anzeigen -> Tabelle obersteszeile 

Klassenlayer -> bearbeiten -> eingaben felder

Klassenlayer ->neue Klasse -> eingaben felder

Schülerlayer -> oberstezeile

Schülelayer -> anzeigen -> Tabelle obersteszeile

Schülerlayer -> neuer Schüler -> eingaben felder

Bücherlayer -> obersteziele

Bücherlayer-> anzeigen-> price

Bücherlayer -> bearbeiten -> eingaben felder

Bücherlayer -> neues Buch -> eingabe felder

Copielayer-> anzeigen

Copielayer->  bearbeiten -> eingaben felder

Copielayer -> neues Copie -> eingabe felder

**Comment by Xerosia99** [comment]
und natürlich müssen wir noch unsere namen ihrgenwo erwähnen als "künster" diese Programmes

**Comment by KayStipcevic** [comment]
ich bin kein künster du pinkel !
lol
